### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ismaelaarab** [orchestral/auth#30]
When i add  `"orchestra/auth": "3.0.**"` and run composer update i get this error:

`Your requirements could not be resolved to an installable set of packages.`

`Problem 1`
`- The requested package orchestra/auth could not be found in any version, there may be a typo in the package name.`

`Potential causes:`
`- A typo in the package name`
`- The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.`

**Comment by crynobone** [comment]
Lower down you stability level, 3.0 are in beta right now.
