### ISSUE TITLE
run php artisan error when Configuration

### ISSUE THREAD

**Issue by huiralb** [orchestral/auth#33]
i run<code>php artisan</code> in command line showing <code> [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined function Orchestra\Memory\database_path()
</code>
can anyone help?

**Comment by crynobone** [comment]
Which Laravel version are you using right now?

**Comment by huiralb** [comment]
5.0.*

**Comment by crynobone** [comment]
I need to know the exact version. 

```
$ php artisan --version
Laravel Framework version 5.0.27
```

**Comment by huiralb** [comment]
<code>php artisan --version
Laravel Framework version 5.0.13
</code>

**Comment by crynobone** [comment]
`database_path()` was added on `v5.0.22`, <https://github.com/laravel/framework/commit/88a2d917f8ecc5437789cac245147e51fcae8a0b>

You could either upgrade Laravel or use an older Memory component such as <https://github.com/orchestral/memory/releases/tag/v3.0.4>

**Comment by huiralb** [comment]
oke, i choose update laravel to `v5.0.22`
Thanks.
