### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProJobless** [orchestral/auth#35]
No supported encrypter found, i tried manything and no luck...any help?

**Comment by crynobone** [comment]
I definitely need more detail in order to suggest anything. `orchestra/auth` doesn't do any special encryption other than what being done at Laravel level `illuminate/auth`.

**Comment by ProJobless** [comment]
This happen after fresh install. this error log after composer install
===================================================
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 – Adds Nyan formatters)
Writing lock file
Generating autoload files


                                                                             
  [RuntimeException]                                                         
  No supported encrypter found. The cipher and / or key length are invalid.  
                                                                             


Script php artisan clear-compiled handling the post-install-cmd event returned with an error


                      
  [RuntimeException]  
  Error Output:       
                      


create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

**Comment by crynobone** [comment]
Yes, this would happen in any Laravel app if you don't have `APP_KEY` with a valid 32 string characters. Not specifically related to `orchestra/auth`.

Why does this happen? It could be possible that for some reason `composer run-script post-root-package-install` wasn't executed <https://github.com/laravel/laravel/blob/master/composer.json#L41>. It also possible that `composer run-script post-create-project-cmd` wasn't executed <https://github.com/laravel/laravel/blob/master/composer.json#L44>

If you're having this problem when using some sort of CI for running build test, you need to run the following:

```
composer run-script post-root-package-install
composer install --no-scripts 
composer run-script post-create-project-cmd
composer run-script post-install-cmd
```
